// ============================================================
// PROMETHEUS METRICS API - taxbook-pro
// Generated: 2026-01-19
// ============================================================
//
// Exposes application metrics in Prometheus format for scraping.
//
// ENDPOINT:
//   GET /api/metrics - Returns metrics in Prometheus text format
//
// PROMETHEUS SCRAPE CONFIGURATION:
//   scrape_configs:
//     - job_name: 'taxbook-pro'
//       static_configs:
//         - targets: ['your-app-host:3000']
//       metrics_path: '/api/metrics'
//       scheme: 'https'
//
// INCLUDED METRICS:
//   - http_requests_total (counter) - Total HTTP requests
//   - http_request_duration_ms (histogram) - Request latency
//   - http_errors_total (counter) - Total HTTP errors
//   - db_query_duration_ms (histogram) - Database query latency
//   - active_users (gauge) - Currently active users
//   - db_connection_pool (gauge) - Connection pool stats
//
// ============================================================

import { metrics } from "@/lib/observability";

// ============================================================
// ROUTE: GET /api/metrics
// ============================================================

/**
 * Prometheus metrics endpoint.
 *
 * Returns metrics in Prometheus text exposition format:
 * https://prometheus.io/docs/instrumenting/exposition_formats/
 *
 * Example output:
 *   # HELP http_requests_total Total HTTP requests
 *   # TYPE http_requests_total counter
 *   http_requests_total{method="GET",path="/api/users"} 1234
 *
 * Security note: Consider protecting this endpoint in production
 * with IP allowlisting or authentication if metrics contain
 * sensitive information.
 */
export async function GET(): Promise<Response> {
  const output = metrics.exportPrometheus();

  return new Response(output, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
    },
  });
}

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
