'use client';

/**
 * Application Providers - taxbook-pro
 * Generated: 2026-01-19
 *
 * Unified providers wrapper that composes all context providers.
 * This component wraps the entire application to provide:
 * - React Query for server state management
 * - Authentication context
 * - Toast notifications
 * - Internationalization
 * 
 *
 * Import this in your root layout.tsx and wrap children.
 */

import { useState, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { ThemeProvider } from 'next-themes';
import { AuthProvider } from '@/components/auth-guard';
import { Toaster } from '@/components/ui/toast';
import { I18nProvider } from '@/lib/i18n/client';

// ============================================================
// QUERY CLIENT CONFIGURATION
// ============================================================

function makeQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        // Data is considered fresh for 60 seconds
        staleTime: 60 * 1000,
        // Cache data for 5 minutes
        gcTime: 5 * 60 * 1000,
        // Retry failed requests up to 3 times with exponential backoff
        retry: 3,
        retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
        // Refetch on window focus for fresh data
        refetchOnWindowFocus: true,
        // Don't refetch on reconnect by default (can be overridden per-query)
        refetchOnReconnect: false,
      },
      mutations: {
        // Retry mutations once on failure
        retry: 1,
      },
    },
  });
}

// Singleton for browser, new instance for each SSR request
let browserQueryClient: QueryClient | undefined = undefined;

function getQueryClient() {
  if (typeof window === 'undefined') {
    // Server: always make a new query client
    return makeQueryClient();
  }
  // Browser: reuse the same query client
  if (!browserQueryClient) {
    browserQueryClient = makeQueryClient();
  }
  return browserQueryClient;
}

// ============================================================
// PROVIDERS COMPONENT
// ============================================================

interface ProvidersProps {
  readonly children: ReactNode;
}

/**
 * Root providers component that wraps the entire application.
 *
 * Provider nesting order (outermost to innermost):
 * 1. QueryClientProvider - React Query state management
 * 2. I18nProvider - Internationalization
 * 3. AuthProvider - Authentication context
 *
 * The Toaster is rendered as a sibling, not a wrapper.
 *
 * @example
 * // In app/layout.tsx
 * import { Providers } from '@/components/providers';
 *
 * export default function RootLayout({ children }: { children: React.ReactNode }) {
 *   return (
 *     <html lang="en">
 *       <body>
 *         <Providers>{children}</Providers>
 *       </body>
 *     </html>
 *   );
 * }
 */
export function Providers({ children }: ProvidersProps) {
  // Create QueryClient instance that persists across re-renders
  const [queryClient] = useState(() => getQueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <I18nProvider>
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </I18nProvider>
      </ThemeProvider>
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  );
}

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
