#!/bin/bash
#
# Validation Script for taxbook-pro
# Generated by Mental Models SDLC Scaffolder
#
# Validates that this project actually works:
# - Dependencies install
# - TypeScript compiles
# - Build succeeds
# - Tests pass
# - Dev server starts
# - Smoke tests pass
#
# Usage:
#   ./scripts/validate.sh              # Full validation
#   ./scripts/validate.sh --quick      # Skip server tests
#   ./scripts/validate.sh --ci         # CI mode (no colors)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

# Configuration
PORT="${PORT:-3000}"
MAX_STARTUP_WAIT=60
QUICK_MODE=false
CI_MODE=false
SERVER_PID=""

# Parse arguments
for arg in "$@"; do
    case $arg in
        --quick) QUICK_MODE=true ;;
        --ci) CI_MODE=true ;;
    esac
done

# Colors (disabled in CI mode)
if [[ "$CI_MODE" == true ]]; then
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
else
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
fi

# Result tracking
FAILED=0
PASSED=0

log_step() { echo -e "\n${BLUE}▶ $1${NC}"; }
log_pass() { echo -e "${GREEN}✓ $1${NC}"; ((PASSED++)); }
log_fail() { echo -e "${RED}✗ $1${NC}"; ((FAILED++)); }
log_warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

cleanup() {
    if [[ -n "$SERVER_PID" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
        kill "$SERVER_PID" 2>/dev/null || true
    fi
    local port_pid
    port_pid=$(lsof -ti ":$PORT" 2>/dev/null || true)
    if [[ -n "$port_pid" ]]; then
        kill "$port_pid" 2>/dev/null || true
    fi
}
trap cleanup EXIT

echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  taxbook-pro - Validation                              ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"

# 1. Dependencies
log_step "Installing dependencies..."
if npm ci 2>/dev/null || npm install; then
    log_pass "Dependencies installed"
else
    log_fail "Dependencies failed"
fi

# 2. TypeScript
log_step "Type checking..."
if npm run typecheck 2>/dev/null || npx tsc --noEmit; then
    log_pass "No type errors"
else
    log_fail "Type errors found"
fi

# 3. Lint
log_step "Linting..."
if npm run lint 2>/dev/null; then
    log_pass "No lint errors"
else
    log_fail "Lint errors found"
fi

# 4. Build
log_step "Building..."
if npm run build; then
    log_pass "Build successful"
else
    log_fail "Build failed"
fi

# 5. Unit/Integration Tests
log_step "Running tests..."
if npm test -- --run 2>/dev/null || npm test 2>/dev/null; then
    log_pass "Tests passed"
else
    log_fail "Tests failed"
fi

# 6. Database Tests (if available)
if grep -q '"test:db"' package.json 2>/dev/null; then
    log_step "Running database tests..."
    if npm run test:db; then
        log_pass "Database tests passed"
    else
        log_fail "Database tests failed"
    fi
fi

# Skip server tests in quick mode
if [[ "$QUICK_MODE" == true ]]; then
    log_warn "Skipping server tests (quick mode)"
else
    # 7. Start dev server
    log_step "Starting dev server on port $PORT..."

    # Kill any existing process
    local port_pid
    port_pid=$(lsof -ti ":$PORT" 2>/dev/null || true)
    if [[ -n "$port_pid" ]]; then
        kill "$port_pid" 2>/dev/null || true
        sleep 1
    fi

    PORT=$PORT npm run dev > /tmp/dev-server.log 2>&1 &
    SERVER_PID=$!

    # Wait for ready
    waited=0
    ready=false
    while [[ $waited -lt $MAX_STARTUP_WAIT ]]; do
        sleep 2
        ((waited+=2))

        if ! kill -0 "$SERVER_PID" 2>/dev/null; then
            log_fail "Server crashed on startup"
            cat /tmp/dev-server.log | tail -20
            break
        fi

        if curl -s -o /dev/null "http://localhost:$PORT" 2>/dev/null; then
            ready=true
            break
        fi
        echo "  Waiting... ($waited/$MAX_STARTUP_WAIT)"
    done

    if [[ "$ready" == true ]]; then
        log_pass "Dev server started in ${waited}s"

        # 8. Smoke tests
        log_step "Running smoke tests..."
        endpoints=(
            "/"
            "/api/health"
            "/api/profile"
            "/api/client"
            "/api/service"
            "/api/appointment"
            "/api/availability"
            "/api/document"
        )

        smoke_failed=0
        for endpoint in "${endpoints[@]}"; do
            status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:$PORT$endpoint" 2>/dev/null || echo "000")
            case "$status" in
                200|201|204|301|302|304|401|403)
                    echo -e "  ${GREEN}✓${NC} $endpoint -> $status"
                    ;;
                404)
                    echo -e "  ${YELLOW}?${NC} $endpoint -> $status (not found)"
                    ;;
                *)
                    echo -e "  ${RED}✗${NC} $endpoint -> $status"
                    ((smoke_failed++))
                    ;;
            esac
        done

        if [[ $smoke_failed -eq 0 ]]; then
            log_pass "Smoke tests passed"
        else
            log_fail "Smoke tests: $smoke_failed endpoints failed"
        fi

        # 9. E2E tests (if Playwright available)
        if [[ -f "playwright.config.ts" ]]; then
            log_step "Running E2E tests..."
            if npx playwright test --reporter=list; then
                log_pass "E2E tests passed"
            else
                log_fail "E2E tests failed"
            fi
        fi
    else
        log_fail "Server did not start within $MAX_STARTUP_WAIT seconds"
    fi
fi

# 10. Security audit
log_step "Security audit..."
audit_output=$(npm audit --json 2>&1 || true)
critical=$(echo "$audit_output" | grep -o '"critical":[0-9]*' | grep -o '[0-9]*' || echo "0")
high=$(echo "$audit_output" | grep -o '"high":[0-9]*' | grep -o '[0-9]*' || echo "0")

if [[ "$critical" -gt 0 ]]; then
    log_fail "Security: $critical critical vulnerabilities"
elif [[ "$high" -gt 0 ]]; then
    log_warn "Security: $high high vulnerabilities"
else
    log_pass "No critical/high vulnerabilities"
fi

# Final Report
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "  Passed: ${GREEN}$PASSED${NC}  Failed: ${RED}$FAILED${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"

if [[ $FAILED -eq 0 ]]; then
    echo -e "\n${GREEN}✅ ALL CHECKS PASSED - Project is production ready${NC}\n"
    exit 0
else
    echo -e "\n${RED}❌ $FAILED CHECK(S) FAILED - Review before deploying${NC}\n"
    exit 1
fi
