-- ============================================================
-- STORAGE BUCKETS - taxbook-pro
-- Generated: 2026-01-19
-- ============================================================
--
-- Run with: supabase db push
-- Apply AFTER initial schema migration
--
-- ============================================================

-- ============================================================
-- MEDIA BUCKET
-- ============================================================
-- For user-uploaded images and videos

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'taxbook-pro-media',
  'taxbook-pro-media',
  true,  -- Public bucket for serving content
  52428800,  -- 50MB limit
  array['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'video/mp4', 'video/webm']
);

-- RLS Policies for media bucket

-- Anyone can view public media
create policy "Public media is viewable by everyone"
  on storage.objects for select
  using (bucket_id = 'taxbook-pro-media');

-- Users can upload to their own folder (user_id/*)
create policy "Users can upload media"
  on storage.objects for insert
  with check (
    bucket_id = 'taxbook-pro-media' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

-- Users can update their own uploads
create policy "Users can update own media"
  on storage.objects for update
  using (
    bucket_id = 'taxbook-pro-media' and
    auth.uid()::text = (storage.foldername(name))[1]
  );

-- Users can delete their own uploads
create policy "Users can delete own media"
  on storage.objects for delete
  using (
    bucket_id = 'taxbook-pro-media' and
    auth.uid()::text = (storage.foldername(name))[1]
  );




-- ============================================================
-- HELPER FUNCTIONS FOR STORAGE
-- ============================================================

-- Get public URL for a storage object
-- Usage: SELECT get_public_url('bucket-name', 'path/to/file.jpg');
create or replace function get_public_url(bucket text, path text)
returns text as $$
  select concat(
    current_setting('app.settings.supabase_url', true),
    '/storage/v1/object/public/',
    bucket,
    '/',
    path
  );
$$ language sql stable;

-- ============================================================
-- GENERATED BY MENTAL MODELS SDLC
-- ============================================================
